# -*- coding: utf-8 -*-
"""Scrapping Data_Edrin Firdaus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_xCKuCIkiFYA_7KFqjxqGhZTYlpjW5b

# **Mobile Legend Review Analysis Sentiment - by Edrin Firdaus**

## **Preparation**

Disini saya akan melakukan scrapping dari Google Play Store dengan bahasa pemrograman Python.
"""

!pip install google-play-scraper

"""## **Import Library**

Saya akan melakukan import library dari google play scraper dengan berupa data pandas
"""

from google_play_scraper import app

import pandas as pd

import numpy as np

"""## **Scrapping**

Aplikasi yang saya pilih yaitu Sapa warga Jabar Super Apps dengan mengambil semua review yang ada.
"""

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.mobile.legends',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=25000,
    filter_score_with=None
)

"""Saya menggunakan review aplikasi 'Mobile legends Bang Bang' berdasarkan review terbaru dan mengambil 25.000 review pengguna.

## **Review Data**
"""

df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

len(df_busu.index)

"""Save file ke CSV"""

df_busu.to_csv("mobile_legends_review.csv", index = False)